name: generate-snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 必须要有写入权限！

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}  # 确保 checkout 有权限

      - name: Create dist directory
        run: mkdir -p dist

      - name: Generate snake
        uses: Platane/snk@master
        with:
          github_user_name: ${{ github.repository_owner }}  # 或直接写你的用户名
          svg_path: dist/github-contribution-grid-snake.svg
          svg_path_dark: dist/github-contribution-grid-snake-dark.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # 或 secrets.PAT（如果用了 PAT）

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # 或 secrets.PAT
